version: "3"

services:

  postgresdb:
    image: postgres:13.2
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: feiranamao
    networks:
      - feiranamao_network

networks:
  feiranamao_network:
